name: "PR Automation"
on:
- pull_request_target

jobs:
  auto-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Automatically assign reviewers
      if: github.event.action == 'opened'
      uses: kentaro-m/auto-assign-action@v1.2.1
